- hosts: vagrant
  become: yes
  gather_facts: no
  pre_tasks:
    - block:
        - setup:
      rescue:
        - name: install python
          raw: sudo apt-get update && sudo apt-get install -y python-minimal
        - setup:
  roles:
    - vagrant
